### ISSUE TITLE
[BUG][BYT] IPC error when do multiple pipeline playback test on byt nocodec platform.

### ISSUE THREAD

**Issue by Jiangxinx** [thesofproject/sof#1726]
**Describe the bug**
DSP panic when do multiple pipeline playback test on byt nocodec platform.

**To Reproduce**
1.Open terminal1:  aplay -Dhw:0,0 -fS16_LE -c2 -r 48000 /dev/zero -vv -i
```
Playing raw data '/dev/zero' : Signed 16 bit Little Endian, Rate 48000 Hz, Stereo
Hardware PCM card 0 'sof-nocodec' device 0 subdevice 0
Its setup is:
  stream       : PLAYBACK
  access       : RW_INTERLEAVED
  format       : S16_LE
  subformat    : STD
  channels     : 2
  rate         : 48000
  exact rate   : 48000 (48000/1)
  msbits       : 16
  buffer_size  : 16368
  period_size  : 4080
  period_time  : 85000
  tstamp_mode  : NONE
  tstamp_type  : MONOTONIC
  period_step  : 1
  avail_min    : 4080
  period_event : 0
  start_threshold  : 16368
  stop_threshold   : 16368
  silence_threshold: 0
  silence_size : 0
  boundary     : 9214364837600034816
  appl_ptr     : 0
  hw_ptr       : 0
#+                                                 | 00%
```
Open terminal2:  aplay -Dhw:0,1 -fS16_LE -c2 -r 48000 /dev/zero -vv -i
```
Playing raw data '/dev/zero' : Signed 16 bit Little Endian, Rate 48000 Hz, Stereo
Hardware PCM card 0 'sof-nocodec' device 1 subdevice 0
Its setup is:
  stream       : PLAYBACK
  access       : RW_INTERLEAVED
  format       : S16_LE
  subformat    : STD
  channels     : 2
  rate         : 48000
  exact rate   : 48000 (48000/1)
  msbits       : 16
  buffer_size  : 24000
  period_size  : 6000
  period_time  : 125000
  tstamp_mode  : NONE
  tstamp_type  : MONOTONIC
  period_step  : 1
  avail_min    : 6000
  period_event : 0
  start_threshold  : 24000
  stop_threshold   : 24000
  silence_threshold: 0
  silence_size : 0
  boundary     : 6755399441055744000
  appl_ptr     : 0
  hw_ptr       : 0
#+                                                 | 00%
```

2.Then ctrl+c stop  terminal2's playback,and open terminal2's playback again.
terminal2:
```
Playing raw data '/dev/zero' : Signed 16 bit Little Endian, Rate 48000 Hz, Stereo
Hardware PCM card 0 'sof-nocodec' device 1 subdevice 0
Its setup is:
  stream       : PLAYBACK
  access       : RW_INTERLEAVED
  format       : S16_LE
  subformat    : STD
  channels     : 2
  rate         : 48000
  exact rate   : 48000 (48000/1)
  msbits       : 16
  buffer_size  : 24000
  period_size  : 6000
  period_time  : 125000
  tstamp_mode  : NONE
  tstamp_type  : MONOTONIC
  period_step  : 1
  avail_min    : 6000
  period_event : 0
  start_threshold  : 24000
  stop_threshold   : 24000
  silence_threshold: 0
  silence_size : 0
  boundary     : 6755399441055744000
  appl_ptr     : 0
  hw_ptr       : 0
#+                                                 | 00%aplay: pcm_write:2011: write error: Input/output error
```

terminal1:
```
Playing raw data '/dev/zero' : Signed 16 bit Little Endian, Rate 48000 Hz, Stereo
Hardware PCM card 0 'sof-nocodec' device 0 subdevice 0
Its setup is:
  stream       : PLAYBACK
  access       : RW_INTERLEAVED
  format       : S16_LE
  subformat    : STD
  channels     : 2
  rate         : 48000
  exact rate   : 48000 (48000/1)
  msbits       : 16
  buffer_size  : 16368
  period_size  : 4080
  period_time  : 85000
  tstamp_mode  : NONE
  tstamp_type  : MONOTONIC
  period_step  : 1
  avail_min    : 4080
  period_event : 0
  start_threshold  : 16368
  stop_threshold   : 16368
  silence_threshold: 0
  silence_size : 0
  boundary     : 9214364837600034816
  appl_ptr     : 0
  hw_ptr       : 0
#+                                                 | 00%aplay: pcm_write:2011: write error: Input/output error
```
**Reproduction Rate**
30%

**dmesg**
```
[  279.247404] sof-audio-acpi 80860F28:01: ipc rx: 0x90020000: GLB_TRACE_MSG
[  279.247427] sof-audio-acpi 80860F28:01: ipc rx done: 0x90020000: GLB_TRACE_MSG
[  279.271461] sof-audio-acpi 80860F28:01: pcm: trigger stream 1 dir 0 cmd 0
[  279.271482] sof-audio-acpi 80860F28:01: ipc tx: 0x60050000: GLB_STREAM_MSG: TRIG_STOP
[  279.271756] sof-audio-acpi 80860F28:01: error: ipc error for 0x60050000 size 12
[  279.271775]  Media Playback 1: ASoC: trigger FE failed -22
[  279.271817] sof-audio-acpi 80860F28:01: pcm: free stream 1 dir 0
[  279.271836] sof-audio-acpi 80860F28:01: ipc tx: 0x60030000: GLB_STREAM_MSG: PCM_FREE
[  279.272674] sof-audio-acpi 80860F28:01: ipc tx succeeded: 0x60030000: GLB_STREAM_MSG: PCM_FREE
[  279.272818] sof-audio-acpi 80860F28:01: pcm: close stream 1 dir 0
[  279.290636] sof-audio-acpi 80860F28:01: PCM: stream 0 dir 0 DMA position 10848 DAI position 17666208
[  279.747518] sof-audio-acpi 80860F28:01: ipc rx: 0x90020000: GLB_TRACE_MSG
[  279.747541] sof-audio-acpi 80860F28:01: ipc rx done: 0x90020000: GLB_TRACE_MSG
[  279.799443] sof-audio-acpi 80860F28:01: pcm: trigger stream 0 dir 0 cmd 0
[  279.799465] sof-audio-acpi 80860F28:01: ipc tx: 0x60050000: GLB_STREAM_MSG: TRIG_STOP
[  279.799916] sof-audio-acpi 80860F28:01: error: ipc error for 0x60050000 size 12
[  279.799936]  Low Latency: ASoC: trigger FE failed -22
[  279.800049] sof-audio-acpi 80860F28:01: pcm: free stream 0 dir 0
[  279.800065] sof-audio-acpi 80860F28:01: ipc tx: 0x60030000: GLB_STREAM_MSG: PCM_FREE
[  279.800823] sof-audio-acpi 80860F28:01: ipc tx succeeded: 0x60030000: GLB_STREAM_MSG: PCM_FREE
[  279.801030] sof-audio-acpi 80860F28:01: pcm: close stream 0 dir 0
[  280.247647] sof-audio-acpi 80860F28:01: ipc rx: 0x90020000: GLB_TRACE_MSG
[  280.247669] sof-audio-acpi 80860F28:01: ipc rx done: 0x90020000: GLB_TRACE_MSG
[  285.254180] sof-audio-acpi 80860F28:01: pcm: open stream 1 dir 0
[  285.254188] sof-audio-acpi 80860F28:01: period min 192 max 262144 bytes
[  285.254191] sof-audio-acpi 80860F28:01: period count 2 max 32
[  285.254195] sof-audio-acpi 80860F28:01: buffer max 8388608 bytes
[  285.255095] sof-audio-acpi 80860F28:01: rate_min: 48000 rate_max: 48000
[  285.255101] sof-audio-acpi 80860F28:01: channels_min: 2 channels_max: 2
[  285.255107] sof-audio-acpi 80860F28:01: rate_min: 48000 rate_max: 48000
[  285.255111] sof-audio-acpi 80860F28:01: channels_min: 2 channels_max: 2
[  285.255115] sof-audio-acpi 80860F28:01: rate_min: 48000 rate_max: 48000
[  285.255119] sof-audio-acpi 80860F28:01: channels_min: 2 channels_max: 2
[  285.255126] sof-audio-acpi 80860F28:01: pcm: hw params stream 1 dir 0
[  285.255133] sof-audio-acpi 80860F28:01: generating page table for 000000005abfe199 size 0x17700 pages 24
[  285.255138] sof-audio-acpi 80860F28:01: stream_tag 0
[  285.255149] sof-audio-acpi 80860F28:01: ipc tx: 0x60010000: GLB_STREAM_MSG: PCM_PARAMS
[  285.255672] sof-audio-acpi 80860F28:01: ipc tx succeeded: 0x60010000: GLB_STREAM_MSG: PCM_PARAMS
[  285.255681] sof-audio-acpi 80860F28:01: pcm: stream dir 0, posn mailbox offset is 1329816
[  285.263449] sof-audio-acpi 80860F28:01: pcm: trigger stream 1 dir 0 cmd 1
[  285.263459] sof-audio-acpi 80860F28:01: ipc tx: 0x60040000: GLB_STREAM_MSG: TRIG_START
[  285.263589] sof-audio-acpi 80860F28:01: ipc tx succeeded: 0x60040000: GLB_STREAM_MSG: TRIG_START
[  285.264136] sof-audio-acpi 80860F28:01: PCM: stream 1 dir 0 DMA position 0 DAI position 0
[  285.768472] sof-audio-acpi 80860F28:01: pcm: trigger stream 1 dir 0 cmd 0
[  285.768494] sof-audio-acpi 80860F28:01: ipc tx: 0x60050000: GLB_STREAM_MSG: TRIG_STOP
[  285.769643] sof-audio-acpi 80860F28:01: ipc tx succeeded: 0x60050000: GLB_STREAM_MSG: TRIG_STOP
[  285.769662] sof-audio-acpi 80860F28:01: ipc tx: 0x60030000: GLB_STREAM_MSG: PCM_FREE
[  285.769792] sof-audio-acpi 80860F28:01: ipc tx succeeded: 0x60030000: GLB_STREAM_MSG: PCM_FREE
[  285.770741] sof-audio-acpi 80860F28:01: pcm: close stream 1 dir 0
[  286.773466] sof-audio-acpi 80860F28:01: pcm: open stream 1 dir 0
[  286.773474] sof-audio-acpi 80860F28:01: period min 192 max 262144 bytes
[  286.773478] sof-audio-acpi 80860F28:01: period count 2 max 32
[  286.773481] sof-audio-acpi 80860F28:01: buffer max 8388608 bytes
[  286.775107] sof-audio-acpi 80860F28:01: rate_min: 48000 rate_max: 48000
[  286.775113] sof-audio-acpi 80860F28:01: channels_min: 2 channels_max: 2
[  286.775119] sof-audio-acpi 80860F28:01: rate_min: 48000 rate_max: 48000
[  286.775123] sof-audio-acpi 80860F28:01: channels_min: 2 channels_max: 2
[  286.775128] sof-audio-acpi 80860F28:01: rate_min: 48000 rate_max: 48000
[  286.775131] sof-audio-acpi 80860F28:01: channels_min: 2 channels_max: 2
[  286.775139] sof-audio-acpi 80860F28:01: pcm: hw params stream 1 dir 0
[  286.775146] sof-audio-acpi 80860F28:01: generating page table for 000000005abfe199 size 0x17700 pages 24
[  286.775151] sof-audio-acpi 80860F28:01: stream_tag 0
[  286.775162] sof-audio-acpi 80860F28:01: ipc tx: 0x60010000: GLB_STREAM_MSG: PCM_PARAMS
[  286.775632] sof-audio-acpi 80860F28:01: ipc tx succeeded: 0x60010000: GLB_STREAM_MSG: PCM_PARAMS
[  286.775638] sof-audio-acpi 80860F28:01: pcm: stream dir 0, posn mailbox offset is 1329816
[  286.776561] sof-audio-acpi 80860F28:01: pcm: trigger stream 1 dir 0 cmd 1
[  286.776571] sof-audio-acpi 80860F28:01: ipc tx: 0x60040000: GLB_STREAM_MSG: TRIG_START
[  286.776790] sof-audio-acpi 80860F28:01: ipc rx: 0x600a0013: GLB_STREAM_MSG: POSITION
[  286.776811] sof-audio-acpi 80860F28:01: posn : host 0x13800 dai 0x2c900 wall 0x8bbe4a
[  286.776820] sof-audio-acpi 80860F28:01: ipc rx done: 0x600a0013: GLB_STREAM_MSG: POSITION
[  286.776853] sof-audio-acpi 80860F28:01: ipc rx: 0x600a0013: GLB_STREAM_MSG: POSITION
[  286.776872] sof-audio-acpi 80860F28:01: posn : host 0x13800 dai 0x2c900 wall 0x8bbe4a
[  286.776876] sof-audio-acpi 80860F28:01: ipc rx done: 0x600a0013: GLB_STREAM_MSG: POSITION
[  286.776906] sof-audio-acpi 80860F28:01: ipc rx: 0x90020000: GLB_TRACE_MSG
[  286.776916] sof-audio-acpi 80860F28:01: ipc rx done: 0x90020000: GLB_TRACE_MSG
[  286.776974] sof-audio-acpi 80860F28:01: ipc rx: 0x600a0013: GLB_STREAM_MSG: POSITION
[  286.776994] sof-audio-acpi 80860F28:01: posn : host 0x13800 dai 0x2c900 wall 0x8bbe4a
[  286.777009] sof-audio-acpi 80860F28:01: ipc rx done: 0x600a0013: GLB_STREAM_MSG: POSITION
[  286.777058] sof-audio-acpi 80860F28:01: ipc rx: 0x600a0013: GLB_STREAM_MSG: POSITION
[  286.777086] sof-audio-acpi 80860F28:01: posn : host 0x13800 dai 0x2c900 wall 0x8bbe4a
[  286.777091] sof-audio-acpi 80860F28:01: ipc rx done: 0x600a0013: GLB_STREAM_MSG: POSITION
[  286.777121] sof-audio-acpi 80860F28:01: ipc rx: 0x600a0013: GLB_STREAM_MSG: POSITION
[  286.777140] sof-audio-acpi 80860F28:01: posn : host 0x13800 dai 0x2c900 wall 0x8bbe4a
[  286.777144] sof-audio-acpi 80860F28:01: ipc rx done: 0x600a0013: GLB_STREAM_MSG: POSITION
[  286.777179] sof-audio-acpi 80860F28:01: ipc rx: 0x600a0013: GLB_STREAM_MSG: POSITION
[  286.777198] sof-audio-acpi 80860F28:01: posn : host 0x13800 dai 0x2c900 wall 0x8bbe4a
[  286.777202] sof-audio-acpi 80860F28:01: ipc rx done: 0x600a0013: GLB_STREAM_MSG: POSITION
[  286.777233] sof-audio-acpi 80860F28:01: ipc rx: 0x600a0013: GLB_STREAM_MSG: POSITION
[  286.777252] sof-audio-acpi 80860F28:01: posn : host 0x13800 dai 0x2c900 wall 0x8bbe4a
[  286.777256] sof-audio-acpi 80860F28:01: ipc rx done: 0x600a0013: GLB_STREAM_MSG: POSITION
[  286.777290] sof-audio-acpi 80860F28:01: ipc rx: 0x600a0013: GLB_STREAM_MSG: POSITION
[  286.777309] sof-audio-acpi 80860F28:01: posn : host 0x13800 dai 0x2c900 wall 0x8bbe4a
[  286.777313] sof-audio-acpi 80860F28:01: ipc rx done: 0x600a0013: GLB_STREAM_MSG: POSITION
[  286.777346] sof-audio-acpi 80860F28:01: ipc rx: 0x600a0013: GLB_STREAM_MSG: POSITION
[  286.777374] sof-audio-acpi 80860F28:01: posn : host 0x13800 dai 0x2c900 wall 0x8bbe4a
[  286.777390] sof-audio-acpi 80860F28:01: ipc rx done: 0x600a0013: GLB_STREAM_MSG: POSITION
[  286.777433] sof-audio-acpi 80860F28:01: ipc rx: 0x600a0013: GLB_STREAM_MSG: POSITION
[  286.777452] sof-audio-acpi 80860F28:01: posn : host 0x13800 dai 0x2c900 wall 0x8bbe4a
[  286.777456] sof-audio-acpi 80860F28:01: ipc rx done: 0x600a0013: GLB_STREAM_MSG: POSITION
[  286.777488] sof-audio-acpi 80860F28:01: ipc rx: 0x600a0013: GLB_STREAM_MSG: POSITION
[  286.777507] sof-audio-acpi 80860F28:01: posn : host 0x13800 dai 0x2c900 wall 0x8bbe4a
[  286.777511] sof-audio-acpi 80860F28:01: ipc rx done: 0x600a0013: GLB_STREAM_MSG: POSITION
[  286.779093] sof-audio-acpi 80860F28:01: ipc tx succeeded: 0x60040000: GLB_STREAM_MSG: TRIG_START
[  286.779154] sof-audio-acpi 80860F28:01: PCM: stream 1 dir 0 DMA position 19968 DAI position 45632
[  286.779166] sof-audio-acpi 80860F28:01: PCM: stream 1 dir 0 DMA position 19968 DAI position 45632
[  286.780636] sof-audio-acpi 80860F28:01: PCM: stream 1 dir 0 DMA position 19968 DAI position 45632
[  286.782188] sof-audio-acpi 80860F28:01: PCM: stream 1 dir 0 DMA position 19968 DAI position 45632
[  286.783560] sof-audio-acpi 80860F28:01: PCM: stream 1 dir 0 DMA position 19968 DAI position 45632
[  286.784738] sof-audio-acpi 80860F28:01: PCM: stream 1 dir 0 DMA position 19968 DAI position 45632
[  287.387890] sof-audio-acpi 80860F28:01: PCM: stream 1 dir 0 DMA position 19968 DAI position 45632
[  287.894640] sof-audio-acpi 80860F28:01: pcm: trigger stream 1 dir 0 cmd 0
[  287.894655] sof-audio-acpi 80860F28:01: ipc tx: 0x60050000: GLB_STREAM_MSG: TRIG_STOP
[  287.895428] sof-audio-acpi 80860F28:01: ipc tx succeeded: 0x60050000: GLB_STREAM_MSG: TRIG_STOP
[  287.895441] sof-audio-acpi 80860F28:01: ipc tx: 0x60030000: GLB_STREAM_MSG: PCM_FREE
[  287.899341] sof-audio-acpi 80860F28:01: ipc tx succeeded: 0x60030000: GLB_STREAM_MSG: PCM_FREE
[  287.899494] sof-audio-acpi 80860F28:01: pcm: close stream 1 dir 0
[  288.468715] sof-audio-acpi 80860F28:01: error : DSP panic!
[  288.468742] sof-audio-acpi 80860F28:01: panic: dsp_oops_offset 1329152 offset 1329152
[  288.468814] sof-audio-acpi 80860F28:01: error: can't enter idle
[  288.468828] sof-audio-acpi 80860F28:01: error: trace point 00000000
[  288.468841] sof-audio-acpi 80860F28:01: error: panic at .../work/sof.git/src/lib/agent.c=:61
[  288.468854] sof-audio-acpi 80860F28:01: error: DSP Firmware Oops
[  288.468871] sof-audio-acpi 80860F28:01: EXCCAUSE 0x0000003f EXCVADDR 0x00000000 PS       0x00060725 SAR     0x00000000
[  288.468887] sof-audio-acpi 80860F28:01: EPC1     0x00000000 EPC2     0x00000000 EPC3     0xff2ce889 EPC4    0xff2ce889
[  288.468902] sof-audio-acpi 80860F28:01: EPC5     0xff2ce884 EPC6     0x00000000 EPC7     0x00000000 DEPC    0x00000000
[  288.468917] sof-audio-acpi 80860F28:01: EPS2     0x00000000 EPS3     0x00060720 EPS4     0x00060720 EPS5    0x00060720
[  288.468932] sof-audio-acpi 80860F28:01: EPS6     0x00000000 EPS7     0x00000000 INTENABL 0x00000000 INTERRU 0x000000a2
[  288.469000] sof-audio-acpi 80860F28:01: stack dump from 0xff327c70
[  288.469025] sof-audio-acpi 80860F28:01: 0xff327c70: ff327c90 00000000 3bdb791c 00000001
[  288.469043] sof-audio-acpi 80860F28:01: 0xff327c74: 6567612f 632e746e 0000003d 00000000
[  288.469061] sof-audio-acpi 80860F28:01: 0xff327c78: 725dd700 acdd5c87 72a44028 ffff987a
[  288.469079] sof-audio-acpi 80860F28:01: 0xff327c7c: c067ebaf ffffffff 00000000 00000000
[  288.469097] sof-audio-acpi 80860F28:01: 0xff327c80: 747fc2a4 ffff987a bd4bb77c ffffffff
[  288.469115] sof-audio-acpi 80860F28:01: 0xff327c84: bd4bb860 ffffffff 725dd700 acdd5c87
[  288.469133] sof-audio-acpi 80860F28:01: 0xff327c88: bd486a6e ffffffff 36793878 ffff987a
[  288.469151] sof-audio-acpi 80860F28:01: 0xff327c8c: bde00205 ffffffff 00000000 00000000
[  288.469164] sof-audio-acpi 80860F28:01: error: waking up any trace sleepers
[  288.854654] sof-audio-acpi 80860F28:01: pcm: open stream 1 dir 0
[  288.854671] sof-audio-acpi 80860F28:01: period min 192 max 262144 bytes
[  288.854681] sof-audio-acpi 80860F28:01: period count 2 max 32
[  288.854690] sof-audio-acpi 80860F28:01: buffer max 8388608 bytes
[  288.863823] sof-audio-acpi 80860F28:01: rate_min: 48000 rate_max: 48000
[  288.863838] sof-audio-acpi 80860F28:01: channels_min: 2 channels_max: 2
[  288.863854] sof-audio-acpi 80860F28:01: rate_min: 48000 rate_max: 48000
[  288.863863] sof-audio-acpi 80860F28:01: channels_min: 2 channels_max: 2
[  288.863875] sof-audio-acpi 80860F28:01: rate_min: 48000 rate_max: 48000
[  288.863884] sof-audio-acpi 80860F28:01: channels_min: 2 channels_max: 2
[  288.863903] sof-audio-acpi 80860F28:01: pcm: hw params stream 1 dir 0
[  288.863919] sof-audio-acpi 80860F28:01: generating page table for 000000005abfe199 size 0x17700 pages 24
[  288.863932] sof-audio-acpi 80860F28:01: stream_tag 0
[  288.864004] sof-audio-acpi 80860F28:01: ipc tx: 0x60010000: GLB_STREAM_MSG: PCM_PARAMS
[  289.365985] sof-audio-acpi 80860F28:01: error: ipc timed out for 0x60010000 size 108
[  289.366055] sof-audio-acpi 80860F28:01: error: can't enter idle
[  289.366060] sof-audio-acpi 80860F28:01: error: trace point 00000000
[  289.366065] sof-audio-acpi 80860F28:01: error: panic at .../work/sof.git/src/lib/agent.c=:61
[  289.366070] sof-audio-acpi 80860F28:01: error: DSP Firmware Oops
[  289.366076] sof-audio-acpi 80860F28:01: EXCCAUSE 0x0000003f EXCVADDR 0x00000000 PS       0x00060725 SAR     0x00000000
[  289.366082] sof-audio-acpi 80860F28:01: EPC1     0x00000000 EPC2     0x00000000 EPC3     0xff2ce889 EPC4    0xff2ce889
[  289.366087] sof-audio-acpi 80860F28:01: EPC5     0xff2ce884 EPC6     0x00000000 EPC7     0x00000000 DEPC    0x00000000
[  289.366093] sof-audio-acpi 80860F28:01: EPS2     0x00000000 EPS3     0x00060720 EPS4     0x00060720 EPS5    0x00060720
[  289.366099] sof-audio-acpi 80860F28:01: EPS6     0x00000000 EPS7     0x00000000 INTENABL 0x00000000 INTERRU 0x000000a2
[  289.366103] sof-audio-acpi 80860F28:01: stack dump from 0xff327c70
[  289.366111] sof-audio-acpi 80860F28:01: 0xff327c70: ff327c90 00000000 3bdb791c 00000001
[  289.366118] sof-audio-acpi 80860F28:01: 0xff327c74: 6567612f 632e746e 0000003d 00000000
[  289.366125] sof-audio-acpi 80860F28:01: 0xff327c78: 3456e100 90dacbcf 365636e8 ffff987a
[  289.366131] sof-audio-acpi 80860F28:01: 0xff327c7c: 00000000 ffffac66 6b4e9880 ffff987a
[  289.366137] sof-audio-acpi 80860F28:01: 0xff327c80: 365636f0 ffff987a 421379f4 ffffac66
[  289.366144] sof-audio-acpi 80860F28:01: 0xff327c84: 73021600 ffff987a 72a44028 ffff987a
[  289.366150] sof-audio-acpi 80860F28:01: 0xff327c88: 36a64a00 ffff987a 3456e100 0000006c
[  289.366157] sof-audio-acpi 80860F28:01: 0xff327c8c: 00000000 00000000 00000000 00000000
[  289.366161] sof-audio-acpi 80860F28:01: error: waking up any trace sleepers
[  289.366168] sof-audio-acpi 80860F28:01: error: hw params ipc failed for stream 0
[  289.366174] sof-audio-acpi 80860F28:01: ASoC: 80860F28:01 hw params failed: -110
[  289.366182]  Media Playback 1: ASoC: hw_params FE failed -110
[  289.366633] sof-audio-acpi 80860F28:01: pcm: close stream 1 dir 0
```

**sof-logger**
```
CORE  LEVEL      COMP_ID                TIMESTAMP            DELTA                FILE_NAME	CONTENT
    0      1         PIPE 0.0     30612240836508420.000000              nan src/audio/pipeline.c:982 	pipeline_task(): xrun recover failed! pipeline will be stopped!
    0      1          DAI 1.9     278566547.812500              nan      src/audio/dai.c:575 	dai_check_for_xrun() error: underrun due to no data available
    0      1         COMP         278566554.791667         6.979167 of/audio/component.h:741 	comp_underrun() error: dev->comp.id = 9, source->avail = 0, copy_bytes = 0
    0      1         PIPE         278566941.718750       386.927094 src/audio/pipeline.c:768 	pipeline_copy() error: ret = -61
    0      1         PIPE 1.10    278566949.895833         8.177083 src/audio/pipeline.c:982 	pipeline_task(): xrun recover failed! pipeline will be stopped!
    0      1         COMP         279074312.031250    507362.125000 rc/audio/component.c:167 	comp_set_state() error: wrong state = 1, COMP_TRIGGER_STOP
    0      1          IPC         279074321.041667         9.010417 src/audio/pipeline.c:639 	pipeline_trigger() error: ret = -22, host->comp.id = 19, cmd = 0
    0      1          IPC         279074331.875000        10.833333    src/ipc/handler.c:486 	ipc: comp 19 trigger 0x50000 failed -22
    0      1         COMP         279602153.697917    527821.812500 rc/audio/component.c:167 	comp_set_state() error: wrong state = 1, COMP_TRIGGER_STOP
    0      1          IPC         279602162.239583         8.541667 src/audio/pipeline.c:639 	pipeline_trigger() error: ret = -22, host->comp.id = 1, cmd = 0
    0      1          IPC         279602173.072917        10.833333    src/ipc/handler.c:486 	ipc: comp 1 trigger 0x50000 failed -22
    0      1          SRC         285064837.395833   5462664.500000  src/audio/src/src.c:763 	No data to process.
    0      1         PIPE         285064844.947917         7.552083 src/audio/pipeline.c:789 	pipeline_copy() error: ret = -5, start->comp.id = 3, dir = 1
    0      1         PIPE 1.10    285064859.010417        14.062500 src/audio/pipeline.c:982 	pipeline_task(): xrun recover failed! pipeline will be stopped!
    0      1          IPC         285445811.979167    380952.968750    src/ipc/handler.c:1251	ipc: msg hdr for 0x600a0013 not found replace 0
    0      1          IPC         285477811.770833     31999.791016    src/ipc/handler.c:1251	ipc: msg hdr for 0x600a0013 not found replace 0
    0      1          IPC         285509811.979167     32000.208984    src/ipc/handler.c:1251	ipc: msg hdr for 0x600a0013 not found replace 0
    0      1          IPC         285541811.979167     32000.000000    src/ipc/handler.c:1251	ipc: msg hdr for 0x600a0013 not found replace 0
    0      1          SRC         286577569.635417   1035757.625000  src/audio/src/src.c:763 	No data to process.
    0      1         PIPE         286577577.135417         7.500000 src/audio/pipeline.c:789 	pipeline_copy() error: ret = -5, start->comp.id = 3, dir = 1
    0      1         PIPE 1.10    286577591.250000        14.114583 src/audio/pipeline.c:982 	pipeline_task(): xrun recover failed! pipeline will be stopped!
    0      2           SA         288268688.645833   1691097.375000      src/lib/agent.c:60  	validate(), idle longer than timeout, delta = 32452464
```

**Environment**
Firmware: c6f1b08 https://github.com/thesofproject/sof/commits/master
Kernel: b45315d5 https://github.com/thesofproject/linux/commits/topic/sof-dev
Topology: sof-byt-nocodec.tplg

**log file**
[dmesg.log](https://github.com/thesofproject/sof/files/3500313/dmesg.log)
[logger.log](https://github.com/thesofproject/sof/files/3500314/logger.log)

**Comment by YvonneYang2** [comment]
Only run command "aplay -Dhw:0,1 -r48000 -c2 -fs16_le /dev/zero -vv -i" can reproduce the issue.

**Reproduced rate**
100%

**Environment**
Firmware: ebf406d0 https://github.com/thesofproject/sof/commits/master
Kernel: a600576c https://github.com/thesofproject/linux/commits/topic/sof-dev
Topology:file: tools/topology/sof-byt-nocodec.tplg

**dmesg**
```
[   90.270089] sof-audio-acpi 80860F28:01: ipc tx succeeded: 0x60040000: GLB_STREAM_MSG: TRIG_START
[   90.270391] sof-audio-acpi 80860F28:01: PCM: stream 1 dir 0 DMA position 0 DAI position 0
[   90.777296] sof-audio-acpi 80860F28:01: pcm: trigger stream 1 dir 0 cmd 0
[   90.777319] sof-audio-acpi 80860F28:01: ipc tx: 0x60050000: GLB_STREAM_MSG: TRIG_STOP
[   90.778275] sof-audio-acpi 80860F28:01: ipc tx succeeded: 0x60050000: GLB_STREAM_MSG: TRIG_STOP
[   90.778294] sof-audio-acpi 80860F28:01: ipc tx: 0x60030000: GLB_STREAM_MSG: PCM_FREE
[   90.778415] sof-audio-acpi 80860F28:01: ipc tx succeeded: 0x60030000: GLB_STREAM_MSG: PCM_FREE
[   90.778597] sof-audio-acpi 80860F28:01: pcm: close stream 1 dir 0
[   91.624193] sof-audio-acpi 80860F28:01: error : DSP panic!
[   91.624205] sof-audio-acpi 80860F28:01: panic: dsp_oops_offset 1329152 offset 1329152
[   91.624269] sof-audio-acpi 80860F28:01: error: can't enter idle
[   91.624275] sof-audio-acpi 80860F28:01: error: trace point 00000000
[   91.624280] sof-audio-acpi 80860F28:01: error: panic at .../work/sof.git/src/lib/agent.c=:61
[   91.624285] sof-audio-acpi 80860F28:01: error: DSP Firmware Oops
[   91.624292] sof-audio-acpi 80860F28:01: EXCCAUSE 0x0000003f EXCVADDR 0x00000000 PS       0x00060725 SAR     0x00000000
[   91.624298] sof-audio-acpi 80860F28:01: EPC1     0x00000000 EPC2     0x00000000 EPC3     0xff2ce8ff EPC4    0xff2ce8ff
[   91.624304] sof-audio-acpi 80860F28:01: EPC5     0xff2ce931 EPC6     0x00000000 EPC7     0x00000000 DEPC    0x00000000
[   91.624310] sof-audio-acpi 80860F28:01: EPS2     0x00000000 EPS3     0x00060720 EPS4     0x00060720 EPS5    0x00060720
[   91.624316] sof-audio-acpi 80860F28:01: EPS6     0x00000000 EPS7     0x00000000 INTENABL 0x00000000 INTERRU 0x000000a2
[   91.624321] sof-audio-acpi 80860F28:01: stack dump from 0xff327c70
[   91.624330] sof-audio-acpi 80860F28:01: 0xff327c70: ff327c90 00000000 5bd6d719 00000000
[   91.624338] sof-audio-acpi 80860F28:01: 0xff327c74: 6567612f 632e746e 0000003d 00000000
[   91.624346] sof-audio-acpi 80860F28:01: 0xff327c78: 0a545e00 dbb7a5f0 345bc828 ffff9e88
[   91.624353] sof-audio-acpi 80860F28:01: 0xff327c7c: c04d9baf ffffffff 00000000 00000000
[   91.624361] sof-audio-acpi 80860F28:01: 0xff327c80: 370932a4 ffff9e88 b8ebb77c ffffffff
[   91.624369] sof-audio-acpi 80860F28:01: 0xff327c84: b8ebb860 ffffffff 0a545e00 dbb7a5f0
[   91.624376] sof-audio-acpi 80860F28:01: 0xff327c88: b8e86a6e ffffffff f6b87038 ffff9e87
[   91.624384] sof-audio-acpi 80860F28:01: 0xff327c8c: b9800205 ffffffff 00000000 00000000
[   91.624389] sof-audio-acpi 80860F28:01: error: waking up any trace sleepers
```
[dmesg.log](https://github.com/thesofproject/sof/files/3514712/dmesg.log)
[logger.log](https://github.com/thesofproject/sof/files/3514713/logger.log)

**Comment by tlauda** [comment]
@YvonneYang2 Fixed by #1722. Could you recheck?

**Comment by Jiangxinx** [comment]
@tlauda This issue still can be reproduced
```
[22762.145698] sof-audio-acpi 80860F28:01: period count 2 max 32
[22762.145701] sof-audio-acpi 80860F28:01: buffer max 8388608 bytes
[22762.146575] sof-audio-acpi 80860F28:01: rate_min: 48000 rate_max: 48000
[22762.146581] sof-audio-acpi 80860F28:01: channels_min: 2 channels_max: 2
[22762.146591] sof-audio-acpi 80860F28:01: pcm: hw params stream 1 dir 0
[22762.146598] sof-audio-acpi 80860F28:01: generating page table for 0000000066bc677a size 0x17700 pages 24
[22762.146603] sof-audio-acpi 80860F28:01: stream_tag 0
[22762.146614] sof-audio-acpi 80860F28:01: ipc tx: 0x60010000: GLB_STREAM_MSG: PCM_PARAMS
[22762.147041] sof-audio-acpi 80860F28:01: ipc tx succeeded: 0x60010000: GLB_STREAM_MSG: PCM_PARAMS
[22762.147049] sof-audio-acpi 80860F28:01: pcm: stream dir 0, posn mailbox offset is 1329816
[22762.148351] sof-audio-acpi 80860F28:01: pcm: trigger stream 1 dir 0 cmd 1
[22762.148362] sof-audio-acpi 80860F28:01: ipc tx: 0x60040000: GLB_STREAM_MSG: TRIG_START
[22762.148460] sof-audio-acpi 80860F28:01: ipc tx succeeded: 0x60040000: GLB_STREAM_MSG: TRIG_START
[22762.148603] sof-audio-acpi 80860F28:01: PCM: stream 1 dir 0 DMA position 0 DAI position 0
[22762.588095] sof-audio-acpi 80860F28:01: ipc rx: 0x90020000: GLB_TRACE_MSG
[22762.588118] sof-audio-acpi 80860F28:01: ipc rx done: 0x90020000: GLB_TRACE_MSG
[22762.657399] sof-audio-acpi 80860F28:01: pcm: trigger stream 1 dir 0 cmd 0
[22762.657422] sof-audio-acpi 80860F28:01: ipc tx: 0x60050000: GLB_STREAM_MSG: TRIG_STOP
[22762.658277] sof-audio-acpi 80860F28:01: error: ipc error for 0x60050000 size 12
[22762.658299]  Media Playback 1: ASoC: trigger FE failed -22
[22762.658351] sof-audio-acpi 80860F28:01: pcm: free stream 1 dir 0
[22762.658368] sof-audio-acpi 80860F28:01: ipc tx: 0x60030000: GLB_STREAM_MSG: PCM_FREE
[22762.658501] sof-audio-acpi 80860F28:01: ipc tx succeeded: 0x60030000: GLB_STREAM_MSG: PCM_FREE
[22762.658621] sof-audio-acpi 80860F28:01: pcm: close stream 1 dir 0
[22762.700511] sof-audio-acpi 80860F28:01: PCM: stream 0 dir 0 DMA position 11632 DAI position 448256
[22763.088251] sof-audio-acpi 80860F28:01: ipc rx: 0x90020000: GLB_TRACE_MSG
[22763.088273] sof-audio-acpi 80860F28:01: ipc rx done: 0x90020000: GLB_TRACE_MSG
[22763.208409] sof-audio-acpi 80860F28:01: pcm: trigger stream 0 dir 0 cmd 0
[22763.208432] sof-audio-acpi 80860F28:01: ipc tx: 0x60050000: GLB_STREAM_MSG: TRIG_STOP
[22763.208703] sof-audio-acpi 80860F28:01: ipc tx succeeded: 0x60050000: GLB_STREAM_MSG: TRIG_STOP
[22763.208718] sof-audio-acpi 80860F28:01: ipc tx: 0x60030000: GLB_STREAM_MSG: PCM_FREE
[22763.208850] sof-audio-acpi 80860F28:01: ipc tx succeeded: 0x60030000: GLB_STREAM_MSG: PCM_FREE
[22763.209005] sof-audio-acpi 80860F28:01: pcm: close stream 0 dir 0
[22763.588337] sof-audio-acpi 80860F28:01: ipc rx: 0x90020000: GLB_TRACE_MSG
[22763.588360] sof-audio-acpi 80860F28:01: ipc rx done: 0x90020000: GLB_TRACE_MSG
```

***Environment***
Firmware: 66da4e89 https://github.com/thesofproject/sof/commits/master
Kernel: 2a22b942 https://github.com/thesofproject/linux/commits/topic/sof-dev
Topology:file: tools/topology/sof-byt-nocodec.tplg

**Comment by tlauda** [comment]
@Jiangxinx Do you still have panic? Because now it looks like problem with simultaneous streaming. Please also apply #1757 and check again.

**Comment by Jiangxinx** [comment]
@tlauda I checked again on byt nocodec platform after #1757 was merged, can't reproduced the DSP panic error, however, the ipc error still exist:
```
[22762.145698] sof-audio-acpi 80860F28:01: period count 2 max 32
[22762.145701] sof-audio-acpi 80860F28:01: buffer max 8388608 bytes
[22762.146575] sof-audio-acpi 80860F28:01: rate_min: 48000 rate_max: 48000
[22762.146581] sof-audio-acpi 80860F28:01: channels_min: 2 channels_max: 2
[22762.146591] sof-audio-acpi 80860F28:01: pcm: hw params stream 1 dir 0
[22762.146598] sof-audio-acpi 80860F28:01: generating page table for 0000000066bc677a size 0x17700 pages 24
[22762.146603] sof-audio-acpi 80860F28:01: stream_tag 0
[22762.146614] sof-audio-acpi 80860F28:01: ipc tx: 0x60010000: GLB_STREAM_MSG: PCM_PARAMS
[22762.147041] sof-audio-acpi 80860F28:01: ipc tx succeeded: 0x60010000: GLB_STREAM_MSG: PCM_PARAMS
[22762.147049] sof-audio-acpi 80860F28:01: pcm: stream dir 0, posn mailbox offset is 1329816
[22762.148351] sof-audio-acpi 80860F28:01: pcm: trigger stream 1 dir 0 cmd 1
[22762.148362] sof-audio-acpi 80860F28:01: ipc tx: 0x60040000: GLB_STREAM_MSG: TRIG_START
[22762.148460] sof-audio-acpi 80860F28:01: ipc tx succeeded: 0x60040000: GLB_STREAM_MSG: TRIG_START
[22762.148603] sof-audio-acpi 80860F28:01: PCM: stream 1 dir 0 DMA position 0 DAI position 0
[22762.588095] sof-audio-acpi 80860F28:01: ipc rx: 0x90020000: GLB_TRACE_MSG
[22762.588118] sof-audio-acpi 80860F28:01: ipc rx done: 0x90020000: GLB_TRACE_MSG
[22762.657399] sof-audio-acpi 80860F28:01: pcm: trigger stream 1 dir 0 cmd 0
[22762.657422] sof-audio-acpi 80860F28:01: ipc tx: 0x60050000: GLB_STREAM_MSG: TRIG_STOP
[22762.658277] sof-audio-acpi 80860F28:01: error: ipc error for 0x60050000 size 12
[22762.658299]  Media Playback 1: ASoC: trigger FE failed -22
[22762.658351] sof-audio-acpi 80860F28:01: pcm: free stream 1 dir 0
[22762.658368] sof-audio-acpi 80860F28:01: ipc tx: 0x60030000: GLB_STREAM_MSG: PCM_FREE
[22762.658501] sof-audio-acpi 80860F28:01: ipc tx succeeded: 0x60030000: GLB_STREAM_MSG: PCM_FREE
[22762.658621] sof-audio-acpi 80860F28:01: pcm: close stream 1 dir 0
[22762.700511] sof-audio-acpi 80860F28:01: PCM: stream 0 dir 0 DMA position 11632 DAI position 448256
[22763.088251] sof-audio-acpi 80860F28:01: ipc rx: 0x90020000: GLB_TRACE_MSG
[22763.088273] sof-audio-acpi 80860F28:01: ipc rx done: 0x90020000: GLB_TRACE_MSG
[22763.208409] sof-audio-acpi 80860F28:01: pcm: trigger stream 0 dir 0 cmd 0
[22763.208432] sof-audio-acpi 80860F28:01: ipc tx: 0x60050000: GLB_STREAM_MSG: TRIG_STOP
[22763.208703] sof-audio-acpi 80860F28:01: ipc tx succeeded: 0x60050000: GLB_STREAM_MSG: TRIG_STOP
[22763.208718] sof-audio-acpi 80860F28:01: ipc tx: 0x60030000: GLB_STREAM_MSG: PCM_FREE
[22763.208850] sof-audio-acpi 80860F28:01: ipc tx succeeded: 0x60030000: GLB_STREAM_MSG: PCM_FREE
[22763.209005] sof-audio-acpi 80860F28:01: pcm: close stream 0 dir 0
[22763.588337] sof-audio-acpi 80860F28:01: ipc rx: 0x90020000: GLB_TRACE_MSG
[22763.588360] sof-audio-acpi 80860F28:01: ipc rx done: 0x90020000: GLB_TRACE_MSG
```

**Comment by lgirdwood** [comment]
@Jiangxinx do things recover after the IPC error if you try again ?

**Comment by Jiangxinx** [comment]
@lgirdwood Yes,it can be recover after I/O error,and this issue also can be reproduced on byt rt5682 platform today.

**Comment by lgirdwood** [comment]
@tlauda looks like we are waiting on DMA emptying ?
```
    0      2          DMA          80057463.802083      1000.000000 src/drivers/dw/dma.c:1301	dw_dma_avail_data_size() size is 0! Channel enable = 0.
    0      2          DMA          80058463.802083      1000.000000 src/drivers/dw/dma.c:1301	dw_dma_avail_data_size() size is 0! Channel enable = 0.
    0      2          DMA          80059463.802083      1000.000000 src/drivers/dw/dma.c:1301	dw_dma_avail_data_size() size is 0! Channel enable = 0.
    0      2          DMA          80060463.802083      1000.000000 src/drivers/dw/dma.c:1301	dw_dma_avail_data_size() size is 0! Channel enable = 0.
    0      2          DMA          80061463.802083      1000.000000 src/drivers/dw/dma.c:1301	dw_dma_avail_data_size() size is 0! Channel enable = 0.
    0      2          DMA          80062463.802083      1000.000000 src/drivers/dw/dma.c:1301	dw_dma_avail_data_size() size is 0! Channel enable = 0.
```

**Comment by juimonen** [comment]
I can reproduce this also. I don't see any obvious error's in the logs. For some reason it looks like that in the error case (start/stop stream 2 during simultaneous stream 1), the stream 1 data feed is disturbed and pipeline stops for xrun. Like the host dma from kernel->dsp is getting jammed for the existing stream->xrun->pipeline stop.

**Comment by juimonen** [comment]
@tlauda so pipeline 0,1 src component _always_ gives me in the beginning: "No data to process. pipeline_task(): xrun recover failed! pipeline will be stopped!". But most of the time pipeline is not stopped, so streams are happily continuing to play... So could it be some timing with pipeline state, that every now and then the pipeline is actually able to stop -> hence we get this error? I can try to modify the src buffering or something to get rid of the message...

**Comment by lgirdwood** [comment]
@juimonen I assume you are using XCC for this debug since it builds a faster SRC for the media pipeline.

**Comment by juimonen** [comment]
@lgirdwood no I'm using gcc. In this use case src should not do any conversion, just copy through

**Comment by juimonen** [comment]
@Jiangxinx @YvonneYang2 can you try this with https://github.com/thesofproject/sof/pull/1834
at least for me it seems to fix the issue.... sometimes this bug is pretty hard to reproduce

**Comment by Jiangxinx** [comment]
@juimonen I tried #1834 on byt nocodec platform, and can't reproduce this issue.

**Comment by Jiangxinx** [comment]
Fixed by #1834 .

**Comment by wenqingfu** [comment]
I found an occurrence in https://sof-ci.01.org/linuxpr/PR1161/build1870/devicetest/ again, but not sure the FW is with #1834 or not.

**Comment by juimonen** [comment]
I think it is with #1834 as I don't see any src complain messages.  This could be another error somehow related to https://github.com/thesofproject/linux/pull/1219. I think we have some occasional jam in ending the stream, which gives input/output error in userspace. I have not found the root cause, but it seems somehow related to the draining/pm_wait... So my suspicion is that it is in upper layers from sof, but haven't figured out yet.
