### ISSUE TITLE
[BUG] SOF docker image has proxy settings hardcoded for Intel network

### ISSUE THREAD

**Issue by kv2019i** [thesofproject/sof#3831]
**Describe the bug**
The current SOF docker images have a hardcoded proxy set to Intel servers:
https://thesofproject.github.io/latest/getting_started/build-guide/build-with-docker.html

While testing the instructions from public network, scripts/docker-run.sh builds will fail due to this. 

** Mitigation **
Modify scripts/docker-run.sh with

````  
+     --env http_proxy \
+     --env https_proxy \
     --env CMAKE_BUILD_TYPE \
```

**Comment by lgirdwood** [comment]
@fredoh9 this is now fixed right ? if so please close.

**Comment by fredoh9** [comment]
@lgirdwood this is not fixed. @marc-hb I agree, we need to keep proxy-free for the docker image and set proxy when needed. I will work on it.
