### ISSUE TITLE
'ipc error' in dmesg log when boot up using nocodec tplg on GordonPeak

### ISSUE THREAD

**Issue by zhuqingliang** [thesofproject/sof#97]
environment:
sof-dev:  a3a39f21218c074c71cd28b0c2c782b1626df3e3
sof:       c454399e8890c1d7eb007857f0dbe018d244eeb7
soft:      47339d2302f445c3b35d50f9720ee649dd2f739b
tplg file name : 
  topology/sof-apl-nocodec.tplg
topology/test/test-ssp5-mclk-0-I2S-volume-s16le-s16le-48k-24576k-nocodec.tplg
topology/test/test-ssp5-mclk-0-I2S-volume-s24le-s24le-48k-24576k-nocodec.tplg

reproduce steps:
check dmesg log once boot up
`dmesg | grep error `

log:
[dmesg4.log](https://github.com/thesofproject/sof/files/2192905/dmesg4.log)
[rmbox4.log](https://github.com/thesofproject/sof/files/2192906/rmbox4.log)

**Comment by tlauda** [comment]
Fixed on master. Please confirm and close.

**Comment by zhuqingliang** [comment]
I test with  c4a9cca0a94969fbf1ecb42d660c0e40279d9ffa . ' ipc error' is still exist.

**Comment by lgirdwood** [comment]
Userspace is trying to set some HW params not supported by the topology. @zhuqingliang what aplay arguments are you using ?

**Comment by xiulipan** [comment]
@zhuqingliang 
If the pulse audio is enabled?
If it does, please disable it and give the log with `--dump-hw-params` in aplay
Such as 

> HW Params of device "hw:0,0":
>--------------------
>ACCESS:  MMAP_INTERLEAVED RW_INTERLEAVED
>FORMAT:  S16_LE S24_LE S32_LE
>SUBFORMAT:  STD
>SAMPLE_BITS: [16 32]
>FRAME_BITS: [32 256]
>CHANNELS: [2 8]
>RATE: 48000
>PERIOD_TIME: [4000 84000]
>PERIOD_SIZE: [192 4032]
>PERIOD_BYTES: [768 16384]
>PERIODS: [2 16]
>BUFFER_TIME: [8000 340000]
>BUFFER_SIZE: [384 16320]
>BUFFER_BYTES: [1536 65536]
>TICK_TIME: ALL
>--------------------


Then try to play each supported format to see if which will hint the same IPC error.
Or start the rmbox trace first and then start the pulse audio.

The rmbox log you uploaded have no error info. Maybe is flushed by other trace.
You can then upload the error trace to find the HW Params that caused the ipc error.

**Comment by zhuqingliang** [comment]
I rename pulseaudio , 'ipc error' is missing.

**Comment by lgirdwood** [comment]
ok, so pulseaudio tries lots of different audio formats when it starts to determine which formats the sound card will accept. In this case PA is trying a format our topology does not accept and the error response is correct.

**Comment by xiulipan** [comment]
@lgirdwood

**Comment by plbossart** [comment]
Can you clarify what the issue is here? I don't get how we can "expose [a] format we did not accept"
I'd suggest adding a log in the kernel to explicitly trace the hw_params requested by the application, so far we see min/max and not the actual value used, which makes it difficult to root cause

**Comment by lgirdwood** [comment]
@xiulipan the pipeline topology can still reject params accepted by the driver as the driver params are only based on the host component and not the full pipeline. The end result is the same to userspace. Please do not re-open issue.

**Comment by xiulipan** [comment]
@plbossart 
for example.
We used to claim we support S16_LE S24_LE and S32_LE for all pass-through topology
But only one will be supported by the pipeline, so there is the same ipc error at that moment.
That bug was fixed by:
https://github.com/thesofproject/soft/commit/b799e3fa3bab7f5df70f2458bda42de167e65fb3
I am just suspecting that we may have some similar PCM_CAPABILITIES issues here.
@lgirdwood 
should not we carefully write the PCM_CAPABILITIES is the topology to avoid these problem?

**Comment by plbossart** [comment]
What? the nocodec topologies are all based on pipelines with volumes, so we can perfectly support S32LE even if the dai doesn't.

**Comment by xiulipan** [comment]
@plbossart 
First, we still have test typologies with no volumes, they are **passthrough** topology
it was true for volume pipelines will support more format, but the problem I mentioned above was for the **passthrough pipelines** test topology
